### ISSUE TITLE
Can't use Store methods outside of function? 

### ISSUE THREAD

**Issue by agstover** [jamiebuilds/unstated-next#15]
With these new changes does that mean we can't do things like import the store on a page and initialize it in a constructor? With NextJS, I was using store methods in getInitialProps which is a pre-render action. 

Notice in example how there's an Store.init(serverState) called to initialize the store in the constructor. 

```js

import App, { Container } from 'next/app'
import React from 'react'
import { Provider } from 'unstated'
import { counterStore } from '../containers/CounterContainer'

class MyApp extends App {
  static async getInitialProps () {
    // do your server state here
    if (!process.browser) {
      // reset state for each request
      counterStore.resetState()
      // process state, in this case counter start with 999
      counterStore.initState(999)
      return { serverState: counterStore.state }
    } else {
      return {}
    }
  }
  constructor (props) {
    super(props)
    // pass the state to client store
    // serverState will be reset when client navigate with Link
    if (process.browser) {
      counterStore.initState(props.serverState.count)
    }
  }
  render () {
    const { Component, pageProps } = this.props
    return (
      <Container>
        <Provider inject={[counterStore]}>
          <Component {...pageProps} />
        </Provider>
      </Container>
    )
  }
}

export default MyApp
```

**Comment by raymondsze** [comment]
React Hooks must live in the lifecycle of React Component.
All states memoized by React Hook are stored in a linked-list according to React implementation.

Unstated is a mock implementation referencing React class component. (i.e, The setState function is not using ReactComponent.setState.) Therefore, unstated allow you to modify its state outside the React Component lifecycle such as Next.js getInitialProps.

Unlike Unstated, Unstated-Next directly use the React Hooks (i.e the Hooks you use inside a function are really using React Hooks). its just a wrapper of mixture of React Context API and React Hooks. That's why it bundled size is even smaller than 1KB.

So, it really stands difference between Unstated and Unstated-Next. I don't think Unstated-next could replace Unstated due to the Hooks limitation.

Another way is to re-implement Unstated-Next by cloning the Hooks implementation that React provides (like what Unstated does).

React can control the Hooks memoized state by global function because all render function are synchronised and at each time only one component could be rendered.

To do so, same kind of assumptions have to made as well for Unstated-Next when cloning the React Hooks.

cc @jamiebuilds

**Comment by jamiebuilds** [comment]
Well, the question here is: Should you even be trying to call container methods?

```js
import React from 'react'
import Counter from './containers/Counter'

function MyApp(props) {
  return (
    <Counter.Provider initialState={props.initialCount}>
      <div>...</div>
    </Counter.Provider>
  )
}

MyApp.getInitialProps = async () => {
  return { initialCount: 999 }
}
```

**Comment by raymondsze** [comment]
Why my comment is deleted? I am not native english speaker, if there are any wording not appropriate, sorry for that.

The following is what I would like to say..

If the question is: **Can't use Store methods outside of function?**
The answer should be **No** as React Hook is living inside functional React Component and **Unstated-Next** is based on React Hooks.

**Is this issue solvable?**
----
Yes and No, to solve this issue, the only way right now is implement the same API like React Hooks provides (may not worth it) and React maintains the whole lifecycle of React component rendering. React could use the global variable reference to implement useXXX hooks. This could only be possible if **Unstated-Next** has the same assumption that React has, but this makes lots of complexity.

**Differences between Unstated and Unstated-Next**
----
**Unstated-Next** use React Hooks directly while **Unstated** create a Container class act like React Component but they are not equal. So you can call function of Container using after "new" outside React and then do the dependency injection back. But this cannot be done in **Unstated-Next**.

**Next.js Example**
----
https://github.com/zeit/next.js/blob/master/examples/with-unstated/pages/_app.js
You can see the api could be persist (resetStore, initStore, as well as custom actions if exists) among server-side and client-side. But this also cannot be done with **Unstated-Next**.

What I would like to say is..
If **Unstated-Next** aims to be a replacement of **Unstated**, the above issue should be an issue.
If **Unstated-Next** is a state management library using React-Hook and have a rule that the state must live in React, then **Unstated-Next** cannot replace **Unstated**.
That's why I think both libraries should be exist.

Just like Context API + Hooks Combo cannot completely replace Redux.

**Comment by jamiebuilds** [comment]
@raymondsze Please move to a different issue

**Comment by raymondsze** [comment]
@jamiebuilds 
Created, https://github.com/jamiebuilds/unstated-next/issues/20.
